version: "3.9"

services:
  telegram_alert_bot:
    build:
      context: .
      network: host
    environment:
      TELEGRAM_BOT_TOKEN: "7632013609:AAFdZpLw4ujGcuYJfY0Z3TGy_jiwI_dI8D4"
      TELEGRAM_GROUP_CHAT_ID: "-1002336176040"
      TELEGRAM_DM_USERS: "6046865555,111111111,222222222"
    ports:
      - "8000:8000"
    restart: always
